---
title: "Продвинутая Эконометрика"
author: "В. Н. Пырлик"
date: "апрель-июнь 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

### Введение
Вы на страничке факультатива **"Продвинутая эконометрика"** для 3 курса группы ПАН в 2022 году. Здесь собраны материалы курса: ссылки на слайды и записи занятий, дополнительные материалы, некоторые обяъвления.

Занятия проходят каждую субботу 9:30-11:30 (Мск) [в Zoom по постоянной ссылке](https://cesnet.zoom.us/j/98157035917).

Записи занятий, слайды, заметки и прочие материалы можно найти по ссылкам ниже.

*Курс в процессе реализации. Страница обновляется по мере появления новых материалов.*

---

### 09.04. Занятие 1. 
#### **Введение в курс. Метод моментов.**

**Введение в курс.** Представление. Формат занятий. Примерное содержание курса. Контроль и оценивание. [**Слайды.**](lec00.html) 

**Лекция 1.** Метод моментов: мотивация и примеры. Классический метод моментов. Оценка методом моментов регрессии на константу и модели множественной линейной регрессии в среднем. Недостаточная, точная и сверхидентификация. [**Слайды.**](lec01.html)

*Видео, к сожалению, записалось без звука.*

---

### 16.04. Занятие 2. 
#### **Обобщенный метод моментов: основы.**

**Лекция 2.** Метод моментов: повторение (примеры). Обобщенный метод моментов: теория. Условия на моменты. Идентификация. Популяционная характеристика и метод аналогии, оценка ОММ. Роль весовой матрицы. Выбор оптимальной матрицы весов - двухшаговый / эффективный ОММ. Примеры оценки ОММ. [**Слайды.**](lec02.html) [**Видео.**](https://drive.google.com/file/d/1cziiyC3SvYME-IuJ5mLvP-VK3M3mbO56/view?usp=sharing)

---

### 23.04. Занятие 3. 
#### **Компьютреная практика: первое применение ОММ**

Простой пример применения ОММ. Обсуждение модели и алгоритма оценки ОММ. Разбор примера на симулированных данных, наблюдение свойств ОММ и эффективного ОММ с ростом размерав выборки. Пример на реальных данных (не успели). [**Слайды.**](lec03.html) [**Видео.**](https://drive.google.com/file/d/11vD55xxDzU3CoAts3zk7c9Db_Hzw-hAa/view?usp=sharing) [**Код.**](pract01.R) [**Данные из последнего примера.**](https://drive.google.com/file/d/1Lz8laThmm9cKXFFWwToQcnj9MyojSixP/view?usp=sharing)

---

#### **Дополнительно**

- [Все записи занятий в одном месте](https://drive.google.com/drive/folders/1sVUQpHBtPKB8BgCkpSrQaVz5B73M677j?usp=sharing)

- [Все слайды в pdf](https://drive.google.com/drive/folders/1PyTMMz86Hln9SN59wq3zY9zmOiqsbKsz?usp=sharing)

- [Страница учебника](https://www.ssc.wisc.edu/~bhansen/econometrics/) и [текст учебника](https://www.ssc.wisc.edu/~bhansen/econometrics/Econometrics.pdf)

- [Материалы компьютерной практики](comp.html)

---

#### *Контакты*

С преподавателем можно свзаться по [электронной почте](mailto:vnpyrlik@hse.ru) и [в Телеграм.](https://t.me/vyrlik)

