---
title: "Продвинутая Эконометрика, апрель-июнь 2022"
subtitle: "Лекция 3. Практический пример"
author: "В. Н. Пырлик"
date: "23 апреля 2022"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: animated, fadeIn
## Сегодня
### Практический пример и компьютерная реализация

 - Постановка задачи, модель
 
 - Демонстрация принципа ОММ (симуляция)
 
 - Кодинг эффективного ОММ
 
 - Пример на реальных данных
 
 - Обсуждение результатов

---
class: animated, fadeIn
## Модель, постановка задачи

$$x_i\sim \text{iid}\:\mathcal{N}(\mu,\sigma^2)$$

--

### Задача
Оценить параметры распределения, учитывая несмещенность и отсутствие избыточного куртозиса у нормального распределения.

--

**Если модель верна,** то

$$\mathbb{E}x=\mu,\;\;\mathbb{E}(x-\mu)^2=\sigma^2,\;\;\mathbb{E}(x-\mu)^3=0,\;\;\mathbb{E}(x-\mu)^4=3\sigma^4$$

---
class: animated, fadeIn
## Модель в терминах ОММ

$$x = x,\;\;\theta=(\mu,\;\sigma^2)',\;\;q=(m,s)',\;\;\theta,q\in R\times R^{+}$$

$$\begin{equation*}
f(x,q) = \left(\begin{matrix} 
   x-m\\
  (x-m)^2-s\\
  (x-m)^3\\
  (x-m)^4-3s^2
\end{matrix}\right) \in R^4
\end{equation*}$$

</br>

--

.rb[2 параметра, 4 условия:] сверхидентификация .right[.rmk[можно использовать ОММ]]

---
class: animated, fadeIn
## Задача оценивания ОММ

$$\hat\theta = \arg\min_{q\in\Theta}\:S_n(q),$$

$$S_n(q) = \overline{f(x_i,q)}^{\text{ }\prime}\:W_n\:\overline{f(x_i,q)}$$

--

$W_n\;-\;$ симметричная, ПО-матрица $4\times4$.

---
class: animated, fadeIn
## Эффективный (двухшаговый ОММ) .rmk[*один из вариантов*]

1. $W_n=I_4$

  - получаем $\hat\theta^{_I}\;-\;$ состоятельную оценку $\theta$

  - оцениваем $W^*$

2. $W_n = \hat W^*_n$

  - получаем $\hat\theta^{_{II}}\;-\;$эффиктивная оценка ОММ

--

3. Можем проверять гипотезы, провести тест на сверхидентификацию, интерпретировать резульатты


---
class: animated, fadeIn
## ЭОММ: шаг I

$$\begin{align*}
S_n(m,s) = & \Big(n^{-1}\sum_i(x_i-m)\Big)^2 + \\
+&\Big(n^{-1}\sum_i((x_i-m)^2-s)\Big)^2 + \\
+&\Big(n^{-1}\sum_i(x-m)^3\Big)^2 + \\
+&\Big(n^{-1}\sum_i((x-m)^4-3s^2)\Big)^2
\end{align*}$$

--

$$\hat\theta^{_I}= \arg\min_{m\in R\\s>0}\:S_n(m,s)$$