---
title: "Продвинутая Эконометрика, апрель-июнь 2022"
subtitle: "Лекция 1. (К)ММ и ОММ"
author: "В. Н. Пырлик"
date: "9 апреля 2022"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: animated, fadeIn
## Сегодня

- Метод Моментов: мотивация

- Простые примеры

- Классический метод моментов

- КММ "vs" МНК

- Первая "оценка" ОММ (пример)

- Сверхидентификация и обобщенный метод моментов

---
class: middle, hands, animated, rotateIn
# .bb[?] Что такое "метод моментов"?

---
class: animated, fadeIn
## Метод моментов: некоторые факты

 - метод оценивания неизвестных параметров
 
    - *работает в рамках параметрического подхода*
 
 - основан на принципе аналогии между </br> теоретическими и выборочными моментами
 
 - работает только в условиях случайных выборок
 
--

</br> </br>

 .rb[!] Один из "фактов" - ложь. .bb[?] Какой?

---
class: animated, fadeIn
## .gb[Пример 1.1] "Регрессия на константу" `r emoji::emoji("vomit")`

--

$$x = \mu + u,\;\mathbb{E}u=0,$$
$x\;-\;$ наблюдаемая величина,

$\mu\;-\;$ неизвестный параметр,

$u\;-\;$ ошибка наблюдения (измерения).

--

Мы наблюдаем результат серии независимых измерений, 

$$\{x_i\}_{i=1,...n}\sim\text{iid}.$$
--

.bb[?] Поставьте задачу оценки неизвестного параметра методом моментов, решите ее, дайте характеристику оценке.

---
class: middle, hands, animated, flipInX

# .bb[?]

## В данной модели "регрессия на константу"
## можем ли мы **протестировать "верна ли модель"**?

---
class: animated, fadeIn
## Классический метод моментов

### 1. Модель

$$\mathbb{E}_xf(x;\theta_o)=0$$

--

### 2. Идентификация

$$\theta \in \Theta \subseteq R^k,\;f(\cdot;\theta):\;R^m\to R^k,\;\text{и} \;\exists!\theta_o\in\Theta:\;\mathbb{E}_xf(x;\theta_o)=0$$
--

### 3. Выборочный контекст

$$x_i\sim\text{iid}$$

--

.bb[?] Распишите в этих терминах "регрессию на константу"

---
class: animated, fadeIn
## Классический метод моментов

...

### 4. Оценка методом моментов:

.center[Такое допустимое значение параметра]

$$\hat\theta\in\Theta,$$

.center[для которого выполняется]

$$n^{-1}\sum_{i=1}^nf(x_i;\hat\theta)=0$$

---
class: hands, animated, flipInY
### Свойства оценок методом моментов

</br> </br>

## .bb[?] Является ли оценка методом моментов

# несмещенной?

---
class: hands, animated, flipInX
### Свойства оценок методом моментов

</br> </br>

## .bb[?] Является ли оценка методом моментов 

# состоятельной?

---
class: hands, animated, flipInY
### Свойства оценок методом моментов

</br> </br>

## .bb[?] Является ли оценка методом моментов

# асимптотически нормальной?

---
class: hands, animated, flipInX
### Свойства оценок методом моментов

</br> </br>

# .bb[?] Что меняется при изменении выборочного контекста?

---
class: animated, fadeIn
## .gb[Пример 2.1] КММ в ММЛР `r emoji::emoji("scared")`

$$y_i = x_i\beta+u_i,\;\mathbb{E}[u_i|x_i]=0,\;\{y_i,x_i,u_i\}\sim\text{iid},\color{blue}{...},$$
$$x_i=(1\;x_{i1}\;...\;x_{ik})',\;\;\beta=(\beta_o\;\beta_1\;...\;\beta_k)'.$$
--

.bb[?] Поставьте задачу оценки методом моментов, найдите решение. Вспомните (дз - найдите) характеристику оценок.

--

.bb[?] Что меняется при изменении выборочного контекста?

--

.bb[?] Можем ли мы проверить "верна ли модель"?

---
class: animated, fadeIn
## .gb[Пример 3] Самая простая сверхидентификация `r emoji::emoji("professor")`

Рассмотрите модель

$$\mathbb{E}y=\mathbb{E}x,\;\{x_i,y_i\}\sim\text{iid},\;\text{и}\;x\;\text{и}\;y\;\text{независимы}.$$

--

.bb[?] Обсудите возможность оценки методом моментов

--

.bb[?] Рассмотрите альтернативную запись модели:

$$\mathbb{E}\left(\begin{matrix}y-\theta_o\\x-\theta_o\end{matrix}\right)=\mathbb{O}_2.$$
Подходит ли классический метод моментов для оценки модели? Обсудите возможные подходы к оцениванию.

---
class: section, animated, zoomIn

## TBC

### До встречи через неделю!
